### ISSUE TITLE
Add whitelist for HTTP sites that are not available via HTTPS

### ISSUE THREAD

**Issue by mp911de** [spring-io/nohttp#10]
The following sites are reported as violations (offline-check) without having a possibility of accessing these via HTTPS:

```
http://stateless.co
http://alps.io
http://www.querydsl.com
http://www.scispike.com
http://www.prowaveconsulting.com
http://narayana.io/
http://www.mybatis.org
```

Also, we're using a DTD from `http://www.mybatis.org/dtd/mybatis-3-mapper.dtd` that needs to be resolved through HTTP.

**Comment by JLLeitschuh** [comment]
> Also, we're using a DTD from http://www.mybatis.org/dtd/mybatis-3-mapper.dtd that needs to be resolved through HTTP.

Please see the security vulnerability email I'm about to send to you (@mp911de) and the pivotal security team.

**Comment by rwinch** [comment]
@mp911de We aren't planning on adding whitelist for sites that aren't available for https. I updated the documentation to make it more clear as to why https://github.com/spring-io/nohttp/tree/master/nohttp#default-whitelist
