### ISSUE TITLE
Standard configuration directory for gradle is /config

### ISSUE THREAD

**Issue by JLLeitschuh** [spring-io/nohttp#11]
I recommend changing the standard directory for configuration from `etc/nohttp` to the standard Gradle configuration directory `config`.

For example, the standard for Gradle's Checkstyle plugin it is `config/checkstyle`, for PMD it is `config/pmd`, for Spotbugs it's `config/spotbugs`.

Consistency would be nice.

**Comment by rwinch** [comment]
Thanks for the report. I'm not sure about changing this now that we have already released, but will give it some consideration.

**Comment by rwinch** [comment]
I switched to support /config folder and deprecated the old location
