### ISSUE TITLE
Expose source as ConfigurableFileTree instead of FileTree

### ISSUE THREAD

**Issue by sdeleuze** [spring-io/nohttp#21]
Gradle Kotlin DSL is more statically typed, when using it it seems it is not possible to update the `source` property of `NoHttpExtension` without an explicit cast like `(source as ConfigurableFileTree).exclude()`.  I think this property should be exposed with type `ConfigurableFileTree` (it seems to use this type internally) instead of `FileTree` to allow such common use case.

**Comment by sbrannen** [comment]
I can confirm that this is needed.

See https://github.com/junit-team/junit5/commit/228002cbb8ec31b43ef39823428ddad43d449824 for details.

**Comment by rwinch** [comment]
Thanks for the report @sdeleuze! Would you be interested in submitting a PR for this?
