### ISSUE TITLE
Allow config location to be explicitly configured via nohttp Gradle extension

### ISSUE THREAD

**Issue by sbrannen** [spring-io/nohttp#23]
Currently, the config location is determined using the following algorithm:

https://github.com/spring-io/nohttp/blob/0ec5484bf2be748e3aac2a7f49fe3aae0bd6d03c/nohttp-gradle/src/main/java/io/spring/nohttp/gradle/NoHttpCheckstylePlugin.java#L180-L190

This works well if you explicitly configure a whitelist file; however, it fails to support a custom configuration location -- for example, `src/nohttp` -- if you only wish to provide a custom `checkstyle.xml` or `suppressions.xml` file.

Ideally, one could specify the location similar to the following.

```groovy
nohttp {
    configLocation "src/nohttp"
}
```

Providing this support would avoid the "Original hack" mentioned in https://github.com/junit-team/junit5/commit/228002cbb8ec31b43ef39823428ddad43d449824.

**Comment by rwinch** [comment]
Thanks for the report @sbrannen!

I'm not sure if this makes sense to provide. The nohttp extension is meant to provide convenience mechanism for defaults for the `checkstyleNohttp` task. If you want, you can configure the `checkstyleNohttp` task directly. For example, the following uses the default `checkstyle.xml` provided by the plugin, but points to a custom `config_loc` to find the `suppressions.xml`:

```groovy
checkstyleNohttp {
	configProperties += ['config_loc': file("custom")]
}
```

**Comment by rwinch** [comment]
I'm going to close this as won't fix. If you have reason that this solution doesn't work, we can consider reopening the issue.
