### ISSUE TITLE
False-positive when an https link includes "http:"

### ISSUE THREAD

**Issue by boris-petrov** [spring-io/nohttp#24]
For example:

https://web.archive.org/web/20091028173024/http://geocities.com/McPoodle43/DVDMaestro/stl_format.html

This should not give a warning but it does.

**Comment by rwinch** [comment]
@JLLeitschuh That is my two cents too. If a project wants to ignore scenarios like this, they can add a whitelist entry to cover it. I'm going to close this as won't fix.
