### ISSUE TITLE
checkstyleNohttp Gradle task uses deprecated API

### ISSUE THREAD

**Issue by sbrannen** [spring-io/nohttp#25]
Using `checkstyleNohttp` in a Gradle 5.4.1 build results in the following deprecation warning.

> Task :checkstyleNohttp
Adding 'config_loc' to checkstyle.configProperties has been deprecated. This is scheduled to be removed in Gradle 6.0. Use checkstyle.configDir instead as this will behave better with up-to-date checks.

**Comment by rwinch** [comment]
Thanks for the report. I have looked into this, but had two problems. First the replacement [configDir](https://docs.gradle.org/current/dsl/org.gradle.api.plugins.quality.CheckstyleExtension.html#org.gradle.api.plugins.quality.CheckstyleExtension:configDir) is incubating. I reached out on the Gradle slack and they said it is probably best to switch even though it is incubating.

However, I ran into a second issue of configDir not configuring the `config_loc`.

**Comment by sbrannen** [comment]
Thanks for looking into it!

And... sorry there doesn't yet seem to be a solution. Hopefully the Gradle will straighten it out.

> However, I ran into a second issue of configDir not configuring the config_loc.

Did you raise an issue against Gradle about that?

**Comment by rwinch** [comment]
@sbrannen I raised two issues. The first is not blocking us, but the second is

* https://github.com/gradle/gradle/issues/9761
* https://github.com/gradle/gradle/issues/9762

**Comment by atomfrede** [comment]
The blocking issue has been fixed :tada:

**Comment by rwinch** [comment]
Thanks it looks like it that will be available in Gradle 6.0

**Comment by rwinch** [comment]
Gradle 6 states that [configDir](https://docs.gradle.org/6.0/dsl/org.gradle.api.plugins.quality.Checkstyle.html#org.gradle.api.plugins.quality.Checkstyle:configDir) is deprecated. I'm not sure what we should do here.

**Comment by wilkinsona** [comment]
I don't think this can be fixed for Gradle 5.x. If we switch from `configProperties.config_loc` to `configDir` then we hit gradle/gradle#9762. We can avoid that problem with Gradle 6 by using `configDirectory`.

It may be worth setting both `configProperties.config_loc` and `configDir` with Gradle 5.x. This will work around gradle/gradle#9762 and hopefully provide better up-to-date checks. The deprecation warning will still appear, but I think that's unavoidable.

**Comment by wilkinsona** [comment]
I think this one's been superseded by #33 and could be closed.
