### ISSUE TITLE
Allow http for all XML namespaces

### ISSUE THREAD

**Issue by larsgrefer** [spring-io/nohttp#30]
I propose to allow http urls in all `xmlns(:.*)?` xml attributes and for every odd (1, 3, 5) url in
in `(.*:)?schemaLocation` xml attributes.

This should be valid:

```
<project xmlns="http://foo.example.com"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://foo.example.com 
                             https://bar.example.com/my-foo-schema.xsd">
```

**Comment by rwinch** [comment]
Thanks for the report @larsgrefer!

This is a good idea, but I don't think it is practical. I don't want nohttp to need to be aware of the content type it is parsing.

**Comment by larsgrefer** [comment]
So we have to whitelist all xml namespaces ever created?

**Comment by rwinch** [comment]
Yes, that is the preferred approach right now. In hindsight, I was a bit harsh. If someone wants to submit a PR for this, I'd accept it on the conditions:

* It is passive
* It works for nohttp and checkstyle
* It does not need to be parsed multiple times

**Comment by larsgrefer** [comment]
With the current line-based approach, its pretty difficult to implement this properly.

The xml attribute name and the xml attribute value could be spread over different lines:
```xml
<foo
xmlns
=
"http://foo.example.com"
>
```

For the `schemaLocation`-attribute it's also very common to have the value spread over different lines.

**Comment by larsgrefer** [comment]
@rwinch What do you think about simplifying the whitelist by using more broad patterns?

https://github.com/spring-io/nohttp/blob/a9c8543ecee6221c097f5584ecb5a9def8cbdf78/nohttp/src/main/resources/io/spring/nohttp/whitelist.txt#L133-L140

could be replaced with `^http://schemas\.microsoft\.com/.*`

https://github.com/spring-io/nohttp/blob/a9c8543ecee6221c097f5584ecb5a9def8cbdf78/nohttp/src/main/resources/io/spring/nohttp/whitelist.txt#L233-L234
and
https://github.com/spring-io/nohttp/blob/a9c8543ecee6221c097f5584ecb5a9def8cbdf78/nohttp/src/main/resources/io/spring/nohttp/whitelist.txt#L237-L245

could be replaced with `^http://xmlns\.jcp\.org/.*`

and so on.

**Comment by rwinch** [comment]
> With the current line-based approach, its pretty difficult to implement this properly.

The implementation does support multiple lines as demonstrated in the [tests](https://github.com/spring-io/nohttp/blob/a9c8543ecee6221c097f5584ecb5a9def8cbdf78/nohttp/src/test/java/io/spring/nohttp/RegexHttpMatcherTest.java#L222).

> What do you think about simplifying the whitelist by using more broad patterns?

I think we can do that, but we need to ensure the file names don't end in `.xsd` or `.dtd`. I'd create a separate ticket for that.

**Comment by larsgrefer** [comment]
> The implementation does support multiple lines as demonstrated in the tests.

`io.spring.nohttp.checkstyle.check.NoHttpCheck` calls `io.spring.nohttp.HttpMatcher#findHttp` with single lines, while `io.spring.nohttp.file.HttpMatcherProcessor` passes the whole file at once.

**Comment by rwinch** [comment]
Yes those things can be changed. However, it will need to ensure it can convey line numbers for checkstyle.
