### ISSUE TITLE
Remove Spring Boot dependency so that Spring Boot can use nohttp without creating a cycle

### ISSUE THREAD

**Issue by wilkinsona** [spring-io/nohttp#35]
Via https://github.com/spring-gradle-plugins/dependency-management-plugin/issues/277, I've just learned that the nohttp project depends on Spring Boot. Spring Boot uses nohttp in its own build, creating a circular dependency between the two projects. Can we please update NoHttp to break this cycle by removing the dependency on Spring Boot? I'd be happy to contribute something.

**Comment by rwinch** [comment]
Thanks for the PR. I'd be happy to accept a pull request

**Comment by rwinch** [comment]
Closing in favor of the pull request gh-36
