### ISSUE TITLE
NoHttpCheckstylePlugin causes all tasks in project to be eagerly configured

### ISSUE THREAD

**Issue by runningcode** [spring-io/nohttp#42]
When applying the plugin to a project, [all tasks in the project are eagerly configured.](
https://ge.jhipster.tech/s/f5dwext7hvonu/performance/configuration?details=code-unit-io.spring.nohttp.gradle.nohttpcheckstyleplugin!:&openScriptsAndPlugins=WyJjb2RlLXVuaXQtaW8uc3ByaW5nLm5vaHR0cC5ncmFkbGUubm9odHRwY2hlY2tzdHlsZXBsdWdpbiJd)

This part eagerly configures all tasks in the project: https://github.com/spring-io/nohttp/blob/master/nohttp-gradle/src/main/java/io/spring/nohttp/gradle/NoHttpCheckstylePlugin.java#L249

Instead we should use `.configureEach`.
See this document for all tasks to avoid: https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

Instead of using tasks.create, use tasks.register.
https://github.com/spring-io/nohttp/blob/master/nohttp-gradle/src/main/java/io/spring/nohttp/gradle/NoHttpCliPlugin.java#L28

**Comment by rwinch** [comment]
Thanks @runningcode! You are right that this is a problem. Would you be interested in submitting a PR?

**Comment by rwinch** [comment]
Since you haven't replied I'm going to put this together so that it can be included in the 0.0.6 release.

**Comment by rwinch** [comment]
Here is a screenshot of [a scan](https://scans.gradle.com/s/ds36vwgupd6im/performance/configuration) running against the latest snapshot that shows only a single task is created when running help.

![image](https://user-images.githubusercontent.com/362503/114246641-bb17c100-9958-11eb-9d79-7f8272920fc7.png)

**Comment by runningcode** [comment]
Thanks so much for getting this done so quickly!
